### ISSUE TITLE
Unable to create new product

### ISSUE THREAD

**Issue by koon29** [microsoft/SDCM#28]
I got no nothing but a timeout when trying to create a new product.

It seems like the following line get stucks for unknown reason:
`L227: DevCenterResponse<Product> ret = await api.NewProduct(createInput.CreateProduct);`

Version 1.0.0.1 - current master.

Here is the output :
```
sdcm.exe -create product.json
SurfaceDevCenterManager v1.0.0.1
> Create Option
Unhandled Exception:
System.OperationCanceledException: The operation was canceled.
   at System.Net.Http.HttpClient.HandleFinishSendAsyncError(Exception e, CancellationTokenSource cts)
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Devices.HardwareDevCenterManager.DevCenterApi.DevCenterHandler.<InvokeHdcService>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Devices.HardwareDevCenterManager.DevCenterApi.DevCenterHandler.<InvokeHdcService>d__11`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Devices.HardwareDevCenterManager.DevCenterApi.DevCenterHandler.<HdcPost>d__13`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Devices.HardwareDevCenterManager.DevCenterApi.DevCenterHandler.<NewProduct>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at SurfaceDevCenterManager.Program.<MainAsync>d__6.MoveNext() in SDCM\SurfaceDevCenterManager\Program.cs:line 227
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SurfaceDevCenterManager.Program.Main(String[] args) in SDCM\SurfaceDevCenterManager\Program.cs:line 60
Last Command:
ERROR (DevCenterErrorDetails)
Code:
HttpCode:
Message:
Correlation Id: 103ed081-cf85-4614-b130-2daf145f2048
Request Id:     b9422e68-e8bb-4f08-9423-3f8110af3a25
Method:         POST
Url:            https://manage.devcenter.microsoft.com/v2.0/my/hardware/products
Content:        {"productName":"Test","test":"Attestation","announcementDate":"2020-10-02T00:00:00","deviceMetadataIds":null,"firmwareVersion":"1","deviceType":"external","isTestSign":false,"isFlightSign":false,"marketingNames":null,"selectedProductTypes":null,"requestedSignatures":["WINDOWS_v100_X64_19H1_FULL"],"additionalAttributes":null,"packageType":null}
Correlation Id: 103ed081-cf85-4614-b130-2daf145f2048
Return: -2 (UNHANDLED_EXCEPTION)
```

authconfig.json conf if OK. (work like a charm with the hardware api)

Tried with both url :
```
https://manage.devcenter.microsoft.com/v1.0/my/hardware/products
https://manage.devcenter.microsoft.com/v2.0/my/hardware/products
```

Still no success.

Is there anything I am missing ?

Thanks

**Comment by flamencist** [comment]
Hi! I hade same issue. After debugging I got answer. My auth was wrong, I used wrong client id.
Try check response via Fiddler (or https monitor)

**Comment by Ben-Carpenter** [comment]
@koon29, are you still having this issue with SDCM?
