### ISSUE TITLE
"Did not find product ID" with SurfaceDevCenterManager v1.0.0.1

### ISSUE THREAD

**Issue by ofarrill** [microsoft/SDCM#32]
Hi,
our since-then untouched build server was not able anymore to submit our driver for Microsofts attestation signing: (last successful submission was September 2021) now it fails at the SDCM stage with:

Time Elapsed 00:00:03.66
Attestation Submission

Create Product
   * Create JSON
   * Submit
Did not find product ID
SurfaceDevCenterManager v1.0.0.1
Create Option
Unhandled Exception:
System.OperationCanceledException: The operation was canceled.
  at System.Net.Http.HttpClient.HandleFinishSendAsyncError(Exception e, CancellationTokenSource cts)
  at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
  at Microsoft.Devices.HardwareDevCenterManager.DevCenterApi.DevCenterHandler.<InvokeHdcService>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at Microsoft.Devices.HardwareDevCenterManager.DevCenterApi.DevCenterHandler.<InvokeHdcService>d__11`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at Microsoft.Devices.HardwareDevCenterManager.DevCenterApi.DevCenterHandler.<HdcPost>d__13`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at Microsoft.Devices.HardwareDevCenterManager.DevCenterApi.DevCenterHandler.<NewProduct>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
  at SurfaceDevCenterManager.Program.<MainAsync>d__6.MoveNext() in <...>:line 227
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at SurfaceDevCenterManager.Program.Main(String[] args) in <...>:line 60
Last Command:
ERROR (DevCenterErrorDetails)
Code:    
HttpCode:
Message: 
Correlation Id: ...
Request Id:     ...
Method:         POST
Url:            https://manage.devcenter.microsoft.com/v2.0/my/hardware/products
Content:        {"productName":"$project_Attestation","testHarness":"Attestation","announcementDate":"2022-02-23T10:28:02","deviceMetadataIds":null,"firmwareVersion":"0","deviceType":"internal","isTestSign":false,"isFlightSign":false,"marketingNames":null,"selectedProductTypes":{"windows_v100_RS4":"Unclassified"},"requestedSignatures":["WINDOWS_v100_X64_TH2_FULL","WINDOWS_v100_X64_RS1_FULL","WINDOWS_v100_X64_RS2_FULL","WINDOWS_v100_X64_RS3_FULL","WINDOWS_v100_X64_RS4_FULL","WINDOWS_v100_X64_RS5_FULL","WINDOWS_v100_X64_19H1_FULL","WINDOWS_v100_X64_VB_FULL"],"additionalAttributes":null,"packageType":null}
Correlation Id: 7a6651b5-10cd-464e-ad1e-005819e862b3
Return: -2 (UNHANDLED_EXCEPTION)
-1

Any hints or ideas are highly appreciated,
thanks!

**Comment by Ben-Carpenter** [comment]
@ofarrill , you are using the latest release is that correct `1.2021.1001.1`? Are you able to attach the full log for this run? Are you running this manually or in a pipeline?

**Comment by Ben-Carpenter** [comment]
@ofarrill , Partner Center has an open issue with their APIs which they are working on. We have created an update for the [Microsoft.Devices.HardwareDevCenterManager](https://www.nuget.org/packages/Microsoft.Devices.HardwareDevCenterManager/) package consumed in this repo. 

The update will catch the HttpRequestException and retry the last command. Please use version 2.2.7 of the package. We will update this repo with the same this week.
