### ISSUE TITLE
signed Package download fails partner center dashboard APIs

### ISSUE THREAD

**Issue by MTKSDCM** [microsoft/SDCM#35]
Correlation Id: c13c419a-f1e8-4e7d-b93d-6d52ccc39d23
Return: 0 (SUCCESS)
> Download File
SurfaceDevCenterManager v1.0.0.1
> Download Option ./DRIVER_sign/MT7961X64.cab.signed.zip
> Fetch Submission Info
Unhandled Exception:
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.Devices.HardwareDevCenterManager.DevCenterApi.DevCenterHandler.<InvokeHdcService>d__9.MoveNext() in C:\Users\DTMLLUAdminUser\Source\Repos\devices-hardware-dev-center-manager\src\Microsoft.Devices.HardwareDevCenterManager\DevCenterHandler.cs:line 125
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Devices.HardwareDevCenterManager.DevCenterApi.DevCenterHandler.<InvokeHdcService>d__10`1.MoveNext() in C:\Users\DTMLLUAdminUser\Source\Repos\devices-hardware-dev-center-manager\src\Microsoft.Devices.HardwareDevCenterManager\DevCenterHandler.cs:line 195
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Devices.HardwareDevCenterManager.DevCenterApi.DevCenterHandler.<HdcGet>d__11`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Devices.HardwareDevCenterManager.DevCenterApi.DevCenterHandler.<GetSubmission>d__18.MoveNext() in C:\Users\DTMLLUAdminUser\Source\Repos\devices-hardware-dev-center-manager\src\Microsoft.Devices.HardwareDevCenterManager\DevCenterHandler.cs:line 301
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at SurfaceDevCenterManager.Program.<MainAsync>d__6.MoveNext() in C:\Users\DTMLLUAdminUser\Downloads\SDCM-main\SDCM-main\SurfaceDevCenterManager\Program.cs:line 590
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SurfaceDevCenterManager.Program.Main(String[] args) in C:\Users\DTMLLUAdminUser\Downloads\SDCM-main\SDCM-main\SurfaceDevCenterManager\Program.cs:line 60
Last Command:

Unhandled Exception: System.MissingFieldException: Field not found: 'Microsoft.Devices.HardwareDevCenterManager.DevCenterApi.DevCenterErrorDetails.Trace'.
   at SurfaceDevCenterManager.Program.DevCenterErrorDetailsDump(DevCenterErrorDetails error)
   at SurfaceDevCenterManager.Program.Main(String[] args) in C:\Users\DTMLLUAdminUser\Downloads\SDCM-main\SDCM-main\SurfaceDevCenterManager\Program.cs:line 67
> Done

**Comment by MTKSDCM** [comment]
This issue is occurring after using the update for the partner center manager

**Comment by MTKSDCM** [comment]
This issue occurs randomly, if any issue is there then it should happen always.
can you please help with it.

i am doubting that there is any issue with Token expiration as well ?

**Comment by Ben-Carpenter** [comment]
The reason this is happening randomly is due to the dependency service which the API calls are made to. We cannot control their service availability.

**Comment by Ben-Carpenter** [comment]
@MTKSDCM, I have been updated that the connection issue has been mitigated. Are you still seeing the issue from your side?

This should resolve your initial title of the issue. Thank you for providing the log. I see the trace filed was not present when you experienced this. We will create a work item to investigate why the trace field was not available.

Unhandled Exception: System.MissingFieldException: `Field not found` : 'Microsoft.Devices.HardwareDevCenterManager.DevCenterApi.DevCenterErrorDetails.`Trace`'.
